baseURL = 'https://bruteforceboy.github.io/'
languageCode = 'en-us'
title = 'Technical Communication'
theme = 'ananke'
canonifyURLs = true

[params]
github = "https://bruteforceboy.github.io/hugo-site/"